BEGIN;

INSERT INTO phrases (urdu_phrase, romanised, meaning_urdu, example_sentence, category, difficulty, image_url, reveal_image_url, is_active)
VALUES
  ('طوطے اڑ جانا', 'Totay ur jana', 'حیران و پریشان رہ جانا', 'جب اسے خبر ملی تو اس کے طوطے اڑ گئے', 'محاورہ', 'آسان', '', '', true),
  ('ہاتھ صاف کرنا', 'Hath saaf karna', 'چوری کرنا یا کوئی چیز غائب کر دینا', 'وہ موقع ملتے ہی ہاتھ صاف کر گیا', 'محاورہ', 'آسان', '', '', true),
  ('دانتوں تلے انگلی دبانا', 'Danton talay ungli dabana', 'بہت زیادہ حیران ہونا', 'اس کا کام دیکھ کر سب نے دانتوں تلے انگلی دبا لی', 'محاورہ', 'درمیانہ', '', '', true),
  ('آنکھوں کا تارا ہونا', 'Ankhon ka tara hona', 'بہت عزیز اور پیارا ہونا', 'یہ بچہ اپنے والدین کی آنکھوں کا تارا ہے', 'محاورہ', 'آسان', '', '', true),
  ('رگوں میں بس جانا', 'Ragon mein bas jana', 'دل و جان میں گہرائی سے سما جانا', 'اس کی آواز میری رگوں میں بس گئی ہے', 'محاورہ', 'مشکل', '', '', true),
  ('چکا چوند ہونا', 'Chaka chaund hona', 'تیز روشنی یا شان و شوکت سے حیران ہو جانا', 'شہر کی روشنیاں دیکھ کر وہ چکا چوند ہو گیا', 'محاورہ', 'درمیانہ', '', '', true),
  ('آگ بگولہ ہونا', 'Aag bagola hona', 'بہت زیادہ غصے میں آ جانا', 'بات سن کر وہ آگ بگولہ ہو گیا', 'محاورہ', 'آسان', '', '', true),
  ('باغ باغ ہونا', 'Bagh bagh hona', 'بہت خوش اور مسرور ہونا', 'خوشخبری سن کر وہ باغ باغ ہو گئے', 'محاورہ', 'آسان', '', '', true),
  ('اونچی دکان پھیکا پکوان', 'Oonchi dukan pheeka pakwan', 'ظاہری دکھاوا زیادہ، اصلیت میں کچھ نہیں', 'اس ہوٹل کا کھانا بے ذائقہ نکلا — اونچی دکان پھیکا پکوان', 'کہاوت', 'درمیانہ', '', '', true),
  ('آگ لگنے پر کنواں کھودنا', 'Aag lagne par kuwan khodna', 'مصیبت آنے کے بعد تیاری کرنا', 'امتحان کے دن پڑھنا شروع کرنا آگ لگنے پر کنواں کھودنا ہے', 'کہاوت', 'درمیانہ', '', '', true),
  ('آستین کا سانپ ہونا', 'Asteen ka sanp hona', 'اپنا بن کر نقصان پہنچانے والا ہونا', 'وہ دوست نہیں نکلا، آستین کا سانپ ثابت ہوا', 'محاورہ', 'درمیانہ', '', '', true),
  ('گڑے مردے اکھاڑنا', 'Ghairay murday ukharna', 'پرانی باتیں چھیڑ دینا', 'ہر بحث میں گڑے مردے اکھاڑنا اچھی بات نہیں', 'محاورہ', 'درمیانہ', '', '', true),
  ('ہاتھ پاؤں مارنا', 'Hath paoun marna', 'بہت کوشش کرنا', 'نوکری کے لیے اس نے بہت ہاتھ پاؤں مارے', 'محاورہ', 'آسان', '', '', true),
  ('کان کھڑے ہونا', 'Kaan kharay hona', 'چوکنا یا ہوشیار ہو جانا', 'مشکوک آواز سنتے ہی اس کے کان کھڑے ہو گئے', 'محاورہ', 'آسان', '', '', true),
  ('ناک میں دم کرنا', 'Naak main dam karna', 'بہت تنگ کرنا', 'بچوں نے شور مچا کر سب کی ناک میں دم کر دیا', 'محاورہ', 'آسان', '', '', true),
  ('پیٹھ پیچھے بات کرنا', 'Peet pichay baat karna', 'غیر موجودگی میں برائی کرنا', 'دوستوں کی پیٹھ پیچھے بات کرنا غلط ہے', 'محاورہ', 'درمیانہ', '', '', true)
ON CONFLICT (urdu_phrase) DO UPDATE SET
  romanised = EXCLUDED.romanised,
  meaning_urdu = EXCLUDED.meaning_urdu,
  example_sentence = EXCLUDED.example_sentence,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  image_url = EXCLUDED.image_url,
  reveal_image_url = EXCLUDED.reveal_image_url,
  is_active = EXCLUDED.is_active;

DELETE FROM wrong_options WHERE phrase_id IN (SELECT id FROM phrases WHERE urdu_phrase IN ('طوطے اڑ جانا', 'ہاتھ صاف کرنا', 'دانتوں تلے انگلی دبانا', 'آنکھوں کا تارا ہونا', 'رگوں میں بس جانا', 'چکا چوند ہونا', 'آگ بگولہ ہونا', 'باغ باغ ہونا', 'اونچی دکان پھیکا پکوان', 'آگ لگنے پر کنواں کھودنا', 'آستین کا سانپ ہونا', 'گڑے مردے اکھاڑنا', 'ہاتھ پاؤں مارنا', 'کان کھڑے ہونا', 'ناک میں دم کرنا', 'پیٹھ پیچھے بات کرنا'));
DELETE FROM phrase_options WHERE phrase_id IN (SELECT id FROM phrases WHERE urdu_phrase IN ('طوطے اڑ جانا', 'ہاتھ صاف کرنا', 'دانتوں تلے انگلی دبانا', 'آنکھوں کا تارا ہونا', 'رگوں میں بس جانا', 'چکا چوند ہونا', 'آگ بگولہ ہونا', 'باغ باغ ہونا', 'اونچی دکان پھیکا پکوان', 'آگ لگنے پر کنواں کھودنا', 'آستین کا سانپ ہونا', 'گڑے مردے اکھاڑنا', 'ہاتھ پاؤں مارنا', 'کان کھڑے ہونا', 'ناک میں دم کرنا', 'پیٹھ پیچھے بات کرنا'));

INSERT INTO wrong_options (phrase_id, option_text)
VALUES
  ((SELECT id FROM phrases WHERE urdu_phrase = 'طوطے اڑ جانا' LIMIT 1), 'بہت خوش اور مسرور ہو جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'طوطے اڑ جانا' LIMIT 1), 'شدید غصے میں آ جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'طوطے اڑ جانا' LIMIT 1), 'اداس اور مایوس ہو جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ صاف کرنا' LIMIT 1), 'کسی معاملے سے بالکل الگ ہو جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ صاف کرنا' LIMIT 1), 'کام ختم کر کے فارغ ہو جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ صاف کرنا' LIMIT 1), 'کسی کو سبق سکھانا یا سزا دینا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'دانتوں تلے انگلی دبانا' LIMIT 1), 'شرمندگی سے پانی پانی ہو جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'دانتوں تلے انگلی دبانا' LIMIT 1), 'بہت زیادہ خوف زدہ ہو جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'دانتوں تلے انگلی دبانا' LIMIT 1), 'غصے سے کانپنے لگنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آنکھوں کا تارا ہونا' LIMIT 1), 'بہت ذہین اور قابل ہونا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آنکھوں کا تارا ہونا' LIMIT 1), 'بہت خوبصورت اور دلکش ہونا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آنکھوں کا تارا ہونا' LIMIT 1), 'گھر میں سب سے بڑا اور ذمہ دار ہونا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'رگوں میں بس جانا' LIMIT 1), 'انتہائی تھکاوٹ اور کمزوری محسوس کرنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'رگوں میں بس جانا' LIMIT 1), 'کسی چیز سے شدید نفرت ہو جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'رگوں میں بس جانا' LIMIT 1), 'جسم میں بیماری پھیل جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'چکا چوند ہونا' LIMIT 1), 'تھکاوٹ اور نیند سے چکرا جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'چکا چوند ہونا' LIMIT 1), 'گھبراہٹ میں کچھ سمجھ نہ آنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'چکا چوند ہونا' LIMIT 1), 'اچانک خوف سے ہوش اڑ جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ بگولہ ہونا' LIMIT 1), 'بہت زیادہ خوشی سے پھولے نہ سمانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ بگولہ ہونا' LIMIT 1), 'شدید محبت میں گرفتار ہو جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ بگولہ ہونا' LIMIT 1), 'ڈر اور خوف سے کانپنے لگنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'باغ باغ ہونا' LIMIT 1), 'بہت غصے میں آ جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'باغ باغ ہونا' LIMIT 1), 'حیران و پریشان رہ جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'باغ باغ ہونا' LIMIT 1), 'شرمندگی سے پانی پانی ہونا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'اونچی دکان پھیکا پکوان' LIMIT 1), 'مہنگی چیز ہمیشہ اچھی ہوتی ہے'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'اونچی دکان پھیکا پکوان' LIMIT 1), 'غریب آدمی کا امیروں جیسا خواب دیکھنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'اونچی دکان پھیکا پکوان' LIMIT 1), 'ہر چیز میں سے بہترین چننا اور باقی چھوڑنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ لگنے پر کنواں کھودنا' LIMIT 1), 'بغیر سوچے سمجھے کوئی قدم اٹھانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ لگنے پر کنواں کھودنا' LIMIT 1), 'دوسروں کی مصیبت میں فائدہ اٹھانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ لگنے پر کنواں کھودنا' LIMIT 1), 'بہت جلدی میں کام کر کے غلطیاں کرنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آستین کا سانپ ہونا' LIMIT 1), 'کسی کو ڈرا کر اپنا کام کروانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آستین کا سانپ ہونا' LIMIT 1), 'ہر وقت خوف میں رہنے والا بزدل شخص'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آستین کا سانپ ہونا' LIMIT 1), 'چھپ کر دوسروں کی باتیں سننے والا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'گڑے مردے اکھاڑنا' LIMIT 1), 'مرے ہوئے لوگوں کو یاد کر کے رونا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'گڑے مردے اکھاڑنا' LIMIT 1), 'پرانی چیزیں جمع کرنے کا شوق رکھنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'گڑے مردے اکھاڑنا' LIMIT 1), 'قبرستان میں جا کر دعا مانگنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ پاؤں مارنا' LIMIT 1), 'لڑائی جھگڑے میں پڑ جانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ پاؤں مارنا' LIMIT 1), 'تیراکی کرتے ہوئے ڈوبنے لگنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ پاؤں مارنا' LIMIT 1), 'کسی کو مار پیٹ کر ڈرانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'کان کھڑے ہونا' LIMIT 1), 'بہت تیز آواز سن کر کان بند کر لینا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'کان کھڑے ہونا' LIMIT 1), 'کسی کی چغلی کھانا اور راز بتانا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'کان کھڑے ہونا' LIMIT 1), 'سننے میں دشواری محسوس کرنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ناک میں دم کرنا' LIMIT 1), 'کسی کو بہت زیادہ خوش کر دینا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ناک میں دم کرنا' LIMIT 1), 'گھر میں خوشبو اور رونق پھیلا دینا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ناک میں دم کرنا' LIMIT 1), 'کسی کی بہت زیادہ تعریف کرنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'پیٹھ پیچھے بات کرنا' LIMIT 1), 'کسی کی مدد خفیہ طور پر کرنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'پیٹھ پیچھے بات کرنا' LIMIT 1), 'منہ پر تعریف اور پیٹھ پیچھے بھی تعریف کرنا'),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'پیٹھ پیچھے بات کرنا' LIMIT 1), 'کسی کے راز کو ہمیشہ چھپا کر رکھنا');

INSERT INTO phrase_options (phrase_id, option_text, is_correct)
VALUES
  ((SELECT id FROM phrases WHERE urdu_phrase = 'طوطے اڑ جانا' LIMIT 1), 'طوطے اڑ جانا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'طوطے اڑ جانا' LIMIT 1), 'کبوتر اڑ جانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'طوطے اڑ جانا' LIMIT 1), 'پرندے بھاگ جانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'طوطے اڑ جانا' LIMIT 1), 'چڑیاں غائب ہونا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ صاف کرنا' LIMIT 1), 'ہاتھ صاف کرنا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ صاف کرنا' LIMIT 1), 'ہاتھ دھو بیٹھنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ صاف کرنا' LIMIT 1), 'ہاتھ ملتے رہنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ صاف کرنا' LIMIT 1), 'ہاتھ کھینچ لینا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'دانتوں تلے انگلی دبانا' LIMIT 1), 'دانتوں تلے انگلی دبانا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'دانتوں تلے انگلی دبانا' LIMIT 1), 'ہونٹوں پر انگلی رکھنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'دانتوں تلے انگلی دبانا' LIMIT 1), 'ناخن سے دانت کاٹنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'دانتوں تلے انگلی دبانا' LIMIT 1), 'زبان سے دانت چھونا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آنکھوں کا تارا ہونا' LIMIT 1), 'آنکھوں کا تارا ہونا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آنکھوں کا تارا ہونا' LIMIT 1), 'آنکھوں کا پانی ہونا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آنکھوں کا تارا ہونا' LIMIT 1), 'نگاہوں کا مرکز ہونا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آنکھوں کا تارا ہونا' LIMIT 1), 'آنکھوں کی روشنی ہونا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'رگوں میں بس جانا' LIMIT 1), 'رگوں میں بس جانا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'رگوں میں بس جانا' LIMIT 1), 'خون کی نالی میں گھر کرنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'رگوں میں بس جانا' LIMIT 1), 'ہڈیوں میں اتر جانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'رگوں میں بس جانا' LIMIT 1), 'سینے میں جڑ پکڑنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'چکا چوند ہونا' LIMIT 1), 'چکا چوند ہونا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'چکا چوند ہونا' LIMIT 1), 'آنکھیں چندھیا جانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'چکا چوند ہونا' LIMIT 1), 'روشنی میں کھو جانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'چکا چوند ہونا' LIMIT 1), 'دھوپ سے اندھا ہونا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ بگولہ ہونا' LIMIT 1), 'آگ بگولہ ہونا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ بگولہ ہونا' LIMIT 1), 'آگ لگنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ بگولہ ہونا' LIMIT 1), 'انگارے اگلنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ بگولہ ہونا' LIMIT 1), 'آگ میں جلنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'باغ باغ ہونا' LIMIT 1), 'باغ باغ ہونا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'باغ باغ ہونا' LIMIT 1), 'پھول کھلنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'باغ باغ ہونا' LIMIT 1), 'گلشن سجنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'باغ باغ ہونا' LIMIT 1), 'چمن بن جانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'اونچی دکان پھیکا پکوان' LIMIT 1), 'اونچی دکان پھیکا پکوان', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'اونچی دکان پھیکا پکوان' LIMIT 1), 'بڑا تھیلا خالی سودا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'اونچی دکان پھیکا پکوان' LIMIT 1), 'چمک دار برتن بے ذائقہ کھانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'اونچی دکان پھیکا پکوان' LIMIT 1), 'اونچی آواز کمزور دلیل', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ لگنے پر کنواں کھودنا' LIMIT 1), 'آگ لگنے پر کنواں کھودنا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ لگنے پر کنواں کھودنا' LIMIT 1), 'سیلاب آنے پر چھت بنانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ لگنے پر کنواں کھودنا' LIMIT 1), 'بارش میں چھتری ڈھونڈنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آگ لگنے پر کنواں کھودنا' LIMIT 1), 'دھوپ نکلنے پر سایہ مانگنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آستین کا سانپ ہونا' LIMIT 1), 'آستین کا سانپ ہونا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آستین کا سانپ ہونا' LIMIT 1), 'جیب میں بچھو رکھنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آستین کا سانپ ہونا' LIMIT 1), 'دامن میں شعلہ چھپانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'آستین کا سانپ ہونا' LIMIT 1), 'گلے کا پھندا بننا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'گڑے مردے اکھاڑنا' LIMIT 1), 'گڑے مردے اکھاڑنا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'گڑے مردے اکھاڑنا' LIMIT 1), 'پرانی راکھ کریدنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'گڑے مردے اکھاڑنا' LIMIT 1), 'بند کتاب کھولنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'گڑے مردے اکھاڑنا' LIMIT 1), 'پرانے زخم سہلانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ پاؤں مارنا' LIMIT 1), 'ہاتھ پاؤں مارنا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ پاؤں مارنا' LIMIT 1), 'ہاتھ پاؤں پھولنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ پاؤں مارنا' LIMIT 1), 'ہاتھ پاؤں جوڑنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ہاتھ پاؤں مارنا' LIMIT 1), 'ہاتھ پاؤں کانپنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'کان کھڑے ہونا' LIMIT 1), 'کان کھڑے ہونا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'کان کھڑے ہونا' LIMIT 1), 'کان میں آواز آنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'کان کھڑے ہونا' LIMIT 1), 'کان لگا کر سننا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'کان کھڑے ہونا' LIMIT 1), 'کان بند کر لینا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ناک میں دم کرنا' LIMIT 1), 'ناک میں دم کرنا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ناک میں دم کرنا' LIMIT 1), 'دم گھونٹ دینا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ناک میں دم کرنا' LIMIT 1), 'ناک رگڑنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'ناک میں دم کرنا' LIMIT 1), 'ناک کٹوانا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'پیٹھ پیچھے بات کرنا' LIMIT 1), 'پیٹھ پیچھے بات کرنا', true),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'پیٹھ پیچھے بات کرنا' LIMIT 1), 'منہ پر بات کرنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'پیٹھ پیچھے بات کرنا' LIMIT 1), 'کان میں سرگوشی کرنا', false),
  ((SELECT id FROM phrases WHERE urdu_phrase = 'پیٹھ پیچھے بات کرنا' LIMIT 1), 'آنکھوں سے اشارہ کرنا', false);

COMMIT;